# fly.toml app configuration file generated for mt-gtm-outbound-agent on 2025-09-13T17:54:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mt-gtm-outbound-agent'
primary_region = 'iad'

[env]
  PYTHONUNBUFFERED = "1"          # ensure logs are flushed immediately

[processes]
  worker = "/app/.venv/bin/python -m scripts.run_worker"

[[services]]
  processes = ['worker']
  internal_port = 8080
  protocol = "tcp"

[[services.http_checks]]
  interval = "15s"
  timeout = "2s"
  method = "GET"
  path = "/health/live"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "dbmate -u \"$DATABASE_URL\" up"
